Fixed arm64 Dockerfile.
Thanks to manfromdownunder and xet7 !

Related #4607,
related #4505

diff --git a/Dockerfile.arm64v8 b/Dockerfile.arm64v8
--- a/Dockerfile.arm64v8
+++ b/Dockerfile.arm64v8
@@ -1,4 +1,5 @@
-FROM amd64/alpine:latest AS builder
+FROM arm64v8/ubuntu:23.04 AS builder
+#FROM amd64/alpine:latest AS builder
 
 # Set the environment variables for builder
 ENV QEMU_VERSION=v7.2.0-1 \
@@ -9,7 +10,9 @@ ENV QEMU_VERSION=v7.2.0-1 \
     WEKAN_ARCHITECTURE=arm64
 
     # Install dependencies
-RUN apk update && apk add ca-certificates outils-sha1 && \
+#RUN apk update && apk add ca-certificates outils-sha1 && \
+RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
+RUN apt update && apt install ca-certificates wget unzip -y && \
     \
     # Download qemu static for our architecture
     wget https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_VERSION}/qemu-${QEMU_ARCHITECTURE}-static.tar.gz -O - | tar -xz && \
@@ -24,7 +27,7 @@ RUN apk update && apk add ca-certificates outils-sha1 && \
     unzip wekan-${WEKAN_VERSION}-${WEKAN_ARCHITECTURE}.zip && \
     \
     # Download node and shasums
-    wget https://github.com/wekan/node-v14-esm/releases/download/${NODE_VERSION}/node-${NODE_VERSION}-${ARCHITECTURE}.tar.gz && \
+    wget https://github.com/wekan/node-v14-esm/releases/download/${NODE_VERSION}/node-${NODE_VERSION}-${NODE_ARCHITECTURE}.tar.gz && \
     wget https://github.com/wekan/node-v14-esm/releases/download/${NODE_VERSION}/SHASUMS256.txt && \
     #wget https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-${NODE_ARCHITECTURE}.tar.gz && \
     #wget https://nodejs.org/dist/${NODE_VERSION}/SHASUMS256.txt.asc && \
@@ -32,7 +35,7 @@ RUN apk update && apk add ca-certificates outils-sha1 && \
     #wget https://nodejs.org/dist/${NODE_VERSION}/SHASUMS256.txt.asc && \
     \
     # Verify nodejs authenticity
-    grep node-${NODE_VERSION}-${NODE_ARCHITECTURE}.tar.gz SHASUMS256.txt.asc | sha256sum -c - && \
+    grep node-${NODE_VERSION}-${NODE_ARCHITECTURE}.tar.gz SHASUMS256.txt | sha256sum -c - && \
     \
     # Extract node and remove tar.gz
     tar xvzf node-${NODE_VERSION}-${NODE_ARCHITECTURE}.tar.gz
@@ -70,16 +73,17 @@ RUN \
     ln -s /opt/nodejs/bin/node /usr/bin/node && \
     ln -s /opt/nodejs/bin/npm /usr/bin/npm && \
     mkdir -p /opt/nodejs/lib/node_modules/fibers/.node-gyp /root/.node-gyp/8.16.1 /home/wekan/.config && \
-    chown wekan --recursive /home/wekan/.config && \
-    \
-    # Install Node dependencies
-    npm install -g npm@${NPM_VERSION} && \
-    \
-    # Install Health Check dependencies
-    apk add curl
+    chown wekan --recursive /home/wekan/.config
 
-HEALTHCHECK --start-period=30s --interval=30s --timeout=10s --retries=3 \
-  CMD curl --fail "http://localhost:$PORT" || exit 1
+#    \
+#    # Install Node dependencies
+#    #npm install -g npm@${NPM_VERSION} && \
+#    \
+#    # Install Health Check dependencies
+#    #apk add curl
+#
+#HEALTHCHECK --start-period=30s --interval=30s --timeout=10s --retries=3 \
+#  CMD curl --fail "http://localhost:$PORT" || exit 1
 
 EXPOSE $PORT
 USER wekan
